apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-pass
  namespace: tp05
  annotations:
    meta.helm.sh/release-name: "my-wordpress"
    meta.helm.sh/release-namespace: "tp05"
  labels:
    app.kubernetes.io/managed-by: "Helm"
spec:
  template:
    metadata:
      name: mysql-pass
      namespace: tp05
      annotations:
        meta.helm.sh/release-name: "my-wordpress"
        meta.helm.sh/release-namespace: "tp05"
      labels:
        app.kubernetes.io/managed-by: "Helm"
    type: Opaque
  encryptedData:
    password: "AgAabMu5gq4CR9kZfEJHJm53s2OtTJyBCZ2zhiAu0GVIx817CkcW7/BaF64+PpBWD6M70BCANlQw8g5dX7KlicJH9krRY5UwllgagX0hrvN6GX16ey0eDs+IZ6deruxc+6zWVMZ/u72HJKxyPnrG2yFe2e3a9/bEw5czCwJfAvg3UbTim5bUb7KG0U+W8CglGEeSOVugkoBf9CF/VFISeMk0uEt4B5bj4Xy8Q2d7eK3kO+rXFL2k0pQI2tC70J0YM4OJqUY9ETvpu1+0EzOCir+RBg2d5w5c0rh+LG0tRvUqTYRQ/OyczgoDlVffz61clwBXfQpbgP8uGcCcMZs1PJ6+XRFUE90chw2W0jKhlQkY7B1/svltiaDavA1NJtVJCbWiTLSAsF8Lh/qWqBufnOZuYWTRHt5jDjIEZqfCNERJ+8LT8iRN+xhCGq97EaxWZa5K/t9MrVe+Dmp8VEwN0Kb4a67DbE6ZD+md/B6VBoV97AOwT/q5V4z/0cQz4PSlaLjkb6etiHoOiRg4JZMrJNizBo/HLQIpvb6OivRbSm9dBiPu+/4Jxg4RO5651XP9HzsCcajeqD4MHN3sqRiq9ByrdcTSW2mG54oMhhLDfacVrdZaf5zhXja1oED7mK2JuLxZTglhEgtAEwR4N9C2mu3NWJEAaBG3dAFz92uWEJkToJBzryOOVsTX9dVU1eY7pXH9hCHmNMaCdNAFT7NJDtIaxljjLBE8Pw=="
